name: Update Site

on:
  schedule:
    - cron: "0 16 * * *"

  workflow_dispatch:

jobs:
  checkIfNew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python 3.8
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - name: Check if metadata has been modified
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import requests

            if os.path.isfile("Last-Modified-SHA.txt"):
                with open(dataDir + "Last-Modified-SHA.txt") as file:
                    prevLastModifiedSha = file.read()
            else:
                prevLastModifiedSha = ""
                
            r = requests.head("https://foss.heptapod.net/api/v4/projects/317/repository/files/metadata%2Fmetadata?ref=branch%2Fdefault")
            lastModifiedSha = r.headers["X-Gitlab-Content-Sha256"]

            if prevLastModifiedSha != lastModifiedSha:
              sys.exit(1)

      - name: Check if metadata has been modified
        run: |
          echo "A little less ${message}"
          echo "A little more action"
          exit 1

      - name: Download metadata/ and thys/
        uses: actions/checkout@main

      - name: Overwrite repo files
        uses: actions/checkout@main

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update metadata and thys"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Hugo
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Generate new site
        run: python plot.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update plots"
          add: "-u"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
