name: Update Site

on:
  schedule:
    - cron: "0 16 * * *"

  workflow_dispatch:
    inputs:
      force:
        description: "Force"
        default: False

jobs:
  updateSite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: carlinmack.github.io

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          cd carlinmack.github.io/.github
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if metadata has been modified
        if: ${{ !(github.event.inputs.force) }}
        run: |
          cd carlinmack.github.io/.github
          python checkMetadata.py

      - name: Checkout site generation repository
        uses: actions/checkout@v2
        with:
          repository: carlinmack/afp
          token: ${{ secrets.AFP_PAT }}
          path: afp

      - name: Download metadata/ and thys/
        run: |
          wget https://foss.heptapod.net/isa-afp/afp-2021/-/archive/branch/default/afp-devel-branch-default.tar.gz?path=thys -O thys.tar.gz &&
          tar -xf thys.tar.gz
          wget https://foss.heptapod.net/isa-afp/afp-2021/-/raw/branch/default/metadata/metadata

      - name: Overwrite repo files
        run: |
          rm -rf afp/src/afp-devel/thys
          mv afp-devel-branch-default-thys/thys afp/src/afp-devel/
          mv -f metadata afp/src/afp-devel/metadata/metadata

      - name: Install dependencies and run exportMetadata.py
        run: |
          cd afp/src/afp-devel/admin
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python exportMetadata.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update metadata and thys"
          branch: "main"
          cwd: "afp"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: |
          cd afp/src/afp-devel/admin/hugo
          hugo --minify --destination $GITHUB_WORKSPACE/carlinmack.github.io/

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update site"
          cwd: "carlinmack.github.io"
          branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
